name: Deploy SSIS Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SQL Server Integration Services
      uses: microsoft/setup-sql-server@v1
      with:
        version: '2019'
        sql-cmd: 'install-ssis'

    - name: Deploy SSIS Package
      run: |
        $password = ConvertTo-SecureString -String ${{ secrets.SSIS_PASSWORD }} -AsPlainText -Force
        $credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'SSIS_USERNAME', $password
        Invoke-Sqlcmd -Credential $credential -Query "EXEC dbo.deploy_ssis_package @package_name = 'package.dtsx', @project_name = 'project.ispac', @folder_name = 'SSISDB', @project_path = '/SSISDB/MyProject/MyFolder'" -ServerInstance $(SSIS_SERVER_NAME)

      env:
        SSIS_SERVER_NAME: ${{ secrets.SSIS_SERVER_NAME }}
        SSIS_USERNAME: ${{ secrets.SSIS_USERNAME }}
        SSIS_PASSWORD: ${{ secrets.SSIS_PASSWORD }}
