name: Remote Database

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mssql-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev

    - name: Wait for MSSQL to start
      run: |
        echo "Waiting for MSSQL server to start..."
        sleep 60

    - name: Run database query from file
      run: |
        sqlcmd -S 192.168.17.1,49172 -U testLogin -P Passw@rd123 -Q "SELECT name FROM master.dbo.sysdatabases"
