name: Check MSSQL Database

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrongPassword"
          MSSQL_PID: "Express"
        ports:
          - "1433:1433"
        options: --name mssql-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MSSQL to start
      run: sleep 20

    - name: Run database tests
      run: |
        # Your database testing commands go here
        # For example:
        sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SHOW DATABASES;"
