name: Check MSSQL Database

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and run MSSQL Docker container
      run: |
       sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrongPassword' -p 1433:1433 -d --name mssql-server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

    - name: Wait for MSSQL to start
      run: |
        echo "Waiting for MSSQL server to start..."
        sleep 60  # Wait for 60 seconds

        # Check if the SQL Server service is ready to accept connections
        for i in {1..5}; do
          if sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SELECT 1" &> /dev/null; then
            echo "MSSQL server is accessible."
            break
          else
            echo "Attempt $i: MSSQL server is not accessible yet."
            docker ps
            sleep 10  # Wait for 10 seconds before retrying
          fi
        done

    - name: Run database query from file
      run: |
        docker exec mssql-server /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrongPassword -i /scripts/your_script.sql
