name: Check MSSQL Database

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrongPassword"
          MSSQL_PID: "Express"
        ports:
          - "1433:1433"
        options: --name mssql-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MSSQL to start
      run: |
        i=0
        until [ $i -ge 30 ]
        do
          echo "Attempting to connect to MSSQL server..."
          if sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SELECT 1;" &> /dev/null; then
            echo "MSSQL server is running."
            break
          else
            i=$((i+1))
            sleep 5
          fi
        done

    - name: Run database query
      run: |
        # Show all databases
        sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SELECT name FROM sys.databases;"

        # Optionally, you can add more SQL queries here to further test your databases
