name: Check MSSQL Database

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/mssql/server:2019-latest
      env:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "YourStrongPassword"
        MSSQL_PID: "Express"
      ports:
        - "1433:1433"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MSSQL to start
      run: |
        echo "Waiting for MSSQL server to start..."
        sleep 60  # Adjust this wait time as needed
        echo "Checking if MSSQL server is accessible..."
        for i in {1..5}; do
          if sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SELECT 1" &> /dev/null; then
            echo "MSSQL server is accessible."
            break
          else
            echo "Attempt $i: MSSQL server is not accessible yet."
            sleep 10
          fi
        done

    - name: Run database query
      run: |
        # Show all databases
        sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SELECT name FROM sys.databases;"

        # Optionally, you can add more SQL queries here to further test your databases
