name: Check MSSQL Database

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and run MSSQL Docker container
      run: |
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrongPassword' -p 1433:1433 -d --name mssql-server mcr.microsoft.com/mssql/server:2019-latest

    - name: Wait for MSSQL to start
      run: |
        echo "Waiting for MSSQL server to start..."
        sleep 220

    - name: Run database query
      run: |
        sqlcmd -S localhost -U SA -P YourStrongPassword -Q "SELECT name FROM sys.databases;"
